spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_server?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: oauth2server
    password: oauth2server@2022
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
  flyway:
    enabled: true
